class Config11 {

        final Map<String, Map<String, ?>> buildConfigurations = [
        x64Mac    : [
            os                  : 'mac',
            arch                : 'x64',
            additionalNodeLabels : 'ci.project.openj9 && hw.arch.x86 && sw.os.mac && sw.tool.xcode.15_2',
            test                : 'default',
            configureArgs       : '--enable-dtrace=auto  --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        x64Linux  : [
            os                  : 'linux',
            arch                : 'x64',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos6_linux-amd64',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.linux',
            dockerNode          : 'sw.tool.docker',
            test                : 'default',
            configureArgs       : '--disable-ccache --enable-dtrace=auto --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        x64Windows: [
            os                  : 'windows',
            arch                : 'x64',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.windows',
            test                : 'default',
            buildArgs           : '--ssh',
            configureArgs       : '--with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition" --with-jdk-rc-name="IBM Semeru Runtime"'
        ],

        ppc64Aix    : [
            os                  : 'aix',
            arch                : 'ppc64',
            additionalNodeLabels: 'hw.arch.ppc64 && sw.os.aix.7_2 && sw.tool.c++runtime.16_1',
            test                : 'default',
            cleanWorkspaceAfterBuild: true,
            configureArgs       : '--with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        s390xLinux    : [
            os                  : 'linux',
            arch                : 's390x',
            test                : 'default',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.s390x'
            dockerImage         : 'sys-rt-docker-local/semeru/s390_rhel7_build_image',
            dockerRegistry      : 'https://docker-na.artifactory.swg-devops.com/',
            dockerCredential    : '7c1c2c28-650f-49e0-afd1-ca6b60479546',
            dockerNode          : 'sw.tool.docker',
            configureArgs       : '--enable-dtrace=auto --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        ppc64leLinux    : [
            os                  : 'linux',
            arch                : 'ppc64le',
            test                : 'default',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.ppc64le && sw.os.linux',
            dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
            dockerNode          : 'sw.tool.docker',
            configureArgs       : '--enable-dtrace=auto --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        aarch64Linux    : [
            os                  : 'linux',
            arch                : 'aarch64',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            dockerNode          : 'sw.tool.docker',
            additionalNodeLabels: 'hw.arch.aarch64 && sw.os.linux',
            test                : 'default',
            configureArgs       : '--enable-dtrace=auto  --without-version-opt  --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
            buildArgs           : '--ssh'
        ],

        aarch64Mac: [
                os                  : 'mac',
                arch                : 'aarch64',
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.aarch64 && sw.os.mac && sw.tool.xcode.15_2',
                cleanWorkspaceAfterBuild: true,
                configureArgs       : '--enable-dtrace --disable-warnings-as-errors --with-noncompressedrefs --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                test                : 'default',
                buildArgs           : '--ssh'
        ],

        x64MacIBM    : [
            os                   : 'mac',
            arch                 : 'x64',
            additionalNodeLabels : 'ci.project.openj9 && hw.arch.x86 && sw.os.mac && sw.tool.xcode.15_2',
            test                 : 'default',
            configureArgs        : '--enable-dtrace=auto ',
            additionalFileNameTag: 'IBM',
            buildArgs            : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        x64LinuxIBM  : [
            os                  : 'linux',
            arch                : 'x64',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos6_linux-amd64',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
            dockerNode          : 'sw.tool.docker',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.linux',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.functional',
                        'sanity.external',
                        'dev.external',
                        'dev.openjdk',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS',
                        'special.jck.fips140_3_OpenJCEPlusFIPS',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3',
                        'special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.external',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ]
            ],
            configureArgs        : '--disable-ccache --enable-dtrace=auto',
            additionalFileNameTag: 'IBM',
            buildArgs            : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        x64WindowsIBM: [
            os                  : 'windows',
            arch                : 'x64',
            additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.windows',
            buildArgs           : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.functional',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS',
                        'special.jck.fips140_3_OpenJCEPlusFIPS',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system'
                    ]
            ],
            configureArgs       : '--with-jdk-rc-name="IBM Semeru Runtime"',
            additionalFileNameTag: 'IBM'
        ],

        ppc64AixIBM    : [
            os                  : 'aix',
            arch                : 'ppc64',
            additionalNodeLabels: 'hw.arch.ppc64 && sw.os.aix.7_2 && sw.tool.c++runtime.16_1',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS',
                        'special.jck.fips140_3_OpenJCEPlusFIPS',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ]
            ],
            additionalFileNameTag    : 'IBM',
            cleanWorkspaceAfterBuild : true,
            buildArgs                : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        s390xLinuxIBM    : [
            os                  : 'linux',
            arch                : 's390x',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.functional',
                        'sanity.external',
                        'dev.external',
                        'dev.openjdk',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS',
                        'special.jck.fips140_3_OpenJCEPlusFIPS',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.external',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ]
            ],
            additionalNodeLabels : 'ci.project.openj9 && hw.arch.s390x',
            dockerImage          : 'sys-rt-docker-local/semeru/s390_rhel7_build_image',
            dockerRegistry       : 'https://docker-na.artifactory.swg-devops.com/',
            dockerCredential     : '7c1c2c28-650f-49e0-afd1-ca6b60479546',
            dockerNode           : 'sw.tool.docker',
            configureArgs        : '--enable-dtrace=auto',
            additionalFileNameTag: 'IBM',
            buildArgs            : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        ppc64leLinuxIBM    : [
            os                  : 'linux',
            arch                : 'ppc64le',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
            dockerNode          : 'sw.tool.docker',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.functional',
                        'sanity.external',
                        'dev.external',
                        'dev.openjdk',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'extended.functional.fips140_3_OpenJCEPlusFIPS',
                        'sanity.jck.fips140_3_OpenJCEPlusFIPS',
                        'extended.jck.fips140_3_OpenJCEPlusFIPS',
                        'special.jck.fips140_3_OpenJCEPlusFIPS',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.external',
                        'sanity.jck.fips140_2',
                        'extended.jck.fips140_2',
                        'special.jck.fips140_2',
                        'sanity.openjdk.fips140_2',
                        'extended.openjdk.fips140_2',
                        'sanity.openjdk.fips140_3_OpenJCEPlusFIPS',
                        'extended.openjdk.fips140_3_OpenJCEPlusFIPS'
                    ]
            ],
            additionalNodeLabels  : 'ci.project.openj9 && hw.arch.ppc64le && sw.os.linux',
            configureArgs         : '--enable-dtrace=auto',
            additionalFileNameTag : 'IBM',
            buildArgs             : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        aarch64LinuxIBM    : [
            os                  : 'linux',
            arch                : 'aarch64',
            dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
            dockerRegistry      : 'https://ghcr.io/',
            dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
            dockerNode          : 'sw.tool.docker',
            additionalNodeLabels: 'hw.arch.aarch64 && sw.os.linux',
            test                : [
                    nightly: [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'special.system'
                    ],
                    weekly : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.functional',
                        'sanity.external',
                        'dev.external',
                        'dev.openjdk'
                    ],
                    release : [
                        'sanity.functional',
                        'sanity.openjdk',
                        'sanity.perf',
                        'sanity.jck',
                        'sanity.system',
                        'extended.functional',
                        'extended.openjdk',
                        'extended.perf',
                        'extended.jck',
                        'extended.system',
                        'special.functional',
                        'special.jck',
                        'special.openjdk',
                        'special.system',
                        'dev.external'
                    ]
            ],
            configureArgs         : '--enable-dtrace=auto  --without-version-opt',
            additionalFileNameTag : 'IBM',
            buildArgs             : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ],

        aarch64MacIBM: [
                os                       : 'mac',
                arch                     : 'aarch64',
                additionalNodeLabels     : 'ci.project.openj9 && hw.arch.aarch64 && sw.os.mac && sw.tool.xcode.15_2',
                cleanWorkspaceAfterBuild : true,
                configureArgs            : '--enable-dtrace --disable-warnings-as-errors --with-noncompressedrefs',
                test                     : 'default',
                additionalFileNameTag    : 'IBM',
                buildArgs                : '--ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk11 -b ibm_sdk'
        ]
  ]

}

Config11 config = new Config11()
return config.buildConfigurations
